import json
import os
from datetime import datetime

with open("sidox/tasks/generated_patch.json") as f:
    patch = json.load(f)

if not patch.get("approved"):
    print("Patch not approved. Waiting for approval.")
    exit()

result = {
    "time": datetime.now().isoformat(),
    "created": [],
    "modified": [],
    "status": "completed"
}

for item in patch["generated_changes"]:

    file = item["file"]

    if item["type"] == "new_file":
        if not os.path.exists(file):
            os.makedirs(os.path.dirname(file), exist_ok=True)

            with open(file, "w") as f:
                f.write("// Generated by Sidox\n")

            result["created"].append(file)

    elif item["type"] == "modify":
        if os.path.exists(file):
            result["modified"].append(file)

with open("sidox/tasks/execution_report.json","w") as f:
    json.dump(result,f,indent=2)

print(json.dumps(result,indent=2))
